# DEFAULT CONTEXT: frontend/

FROM node:20-alpine AS deps
WORKDIR /app

COPY ./package.json ./package-lock.json* ./

RUN npm ci


FROM node:20-alpine AS builder
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1


COPY --from=deps /app/node_modules ./node_modules

COPY . .


RUN npm run build


FROM node:20-alpine
WORKDIR /app

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/static ./.next/static

USER node

EXPOSE 3000
CMD ["node", "server.js"]
