import type { Metadata } from 'next';
import { Montserrat, Roboto, Raleway, Great_Vibes } from 'next/font/google';
import './globals.css';
import Header from '@/components/layout/server/Header';
import Footer from '@/components/layout/server/Footer';

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['cyrillic'],
});
const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['cyrillic'],
});
const raleway = Raleway({
  variable: '--font-raleway',
  subsets: ['cyrillic'],
});
const greatVibes = Great_Vibes({
  weight: '400',
  variable: '--font-great-vibes',
  subsets: ['cyrillic'],
});

export const metadata: Metadata = {
  title: 'Фауна',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${roboto.variable} ${raleway.variable} ${greatVibes.variable} ${montserrat.className} antialiased`}
      >
        <Header />
        <main className="mx-auto max-w-screen-xl">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
